apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-data
  namespace: mediaserver
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: '9999'
    volumeAttributes:
      source: "//sirius.hlspace.org/datashare"
    nodeStageSecretRef:
      name: cifs-secret
      namespace: mediaserver