apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-data
  namespace: mediaserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-smb-data
  storageClassName: ""