version: '3'
services:
  myspeed:
    ports:
      - '5216:5216'
    volumes:
      - 'myspeed:/myspeed/data'
    restart: unless-stopped
    container_name: MySpeed
    image: 'germannewsmaker/myspeed:latest'

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run

volumes:
  myspeed:
    external: false