services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - cifs-volume:/media
    restart: 'unless-stopped'

volumes:
  cifs-volume:
    driver_opts:
      type: cifs
      o: username=${username},password=${password},vers=3.0
      device: //192.168.1.80/datashare/media
