---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
        app: jackett
    spec:
      hostname: jackett
      subdomain: homelab
      containers:
        - name: jackett
          image: lscr.io/linuxserver/jackett
          ports:
            - name: jackett-port
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: hostpath-volume-config
              mountPath: /config
      volumes:

        - name: hostpath-volume-config
          persistentVolumeClaim:
            claimName: hostpath-config
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: jackett
spec:
  type: ClusterIP
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: jackett-port
  selector:
    app: jackett

---
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
spec:
  ingressClassName: nginx
  rules:
    - host: jackett.homelab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117
---


