---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app: jellyfin
    spec:
      hostNetwork: true
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin
          ports:
            - name: jellyfin-port
              containerPort: 8096
              protocol: TCP
          volumeMounts:              
            - name: hostpath-volume
              mountPath: /movies
            - name: hostpath-volume
              mountPath: /tv
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: hostpath-pvc

---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  type: ClusterIP
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
      name: jellyfin-port
  selector:
    app: jellyfin

---
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
spec:
  ingressClassName: nginx
  rules:
    - host: jellyfin.homelab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096
---