---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex
          ports:
            - name: plex-port
              containerPort: 32400
              protocol: TCP
          volumeMounts:              
            - name: hostpath-volume
              mountPath: /movies
              subPath: movies
            - name: hostpath-volume
              mountPath: /tv
              subPath: tv
            - name: hostpath-volume
              mountPath: /music
              subPath: music
            - name: hostpath-volume-config
              mountPath: /config
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: hostpath-pvc
        - name: hostpath-volume-config
          persistentVolumeClaim:
            claimName: hostpath-config
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: ClusterIP
  ports:
    - port: 32400
      targetPort: 32400
      protocol: TCP
      name: plex-port
  selector:
    app: plex

---
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
spec:
  ingressClassName: nginx
  rules:
    - host: plex.homelab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
---


