---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: plex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex
        app: plex
    spec:
      hostNetwork: true
      containers:
        - name: plex
          image: lscr.io/linuxserver/plex
          env:  # < environment variables. See https://hub.docker.com/r/linuxserver/plex
            - name: PGID
              value: "\x31\x30\x30"    # < ASCII code for '100'
            - name: PUID
              value: "\x31\x30\x33\x35" # < ACII code for '1035'
            - name: VERSION
              value: latest
            - name: TZ
              value: Europe/Amsterdam
            - name: PLEX_CLAIM
              value: claim-jBRew1m2HjkuNy_9F-_-
          ports:
            - containerPort: 32400     # < required network portnumber. See https://hub.docker.com/r/linuxserver/plex
              name: pms-web            # < reference name from the port in the service yaml
              protocol: TCP
            - containerPort: 32469
              name: dlna-tcp
              protocol: TCP
            - containerPort: 1900
              name: dlna-udp
              protocol: UDP
            - containerPort: 3005
              name: plex-companion
              protocol: TCP  
            - containerPort: 5353
              name: discovery-udp
              protocol: UDP  
            - containerPort: 8324
              name: plex-roku
              protocol: TCP  
            - containerPort: 32410
              name: gdm-32410
              protocol: UDP
            - containerPort: 32412
              name: gdm-32412
              protocol: UDP
            - containerPort: 32413
              name: gdm-32413
              protocol: UDP
            - containerPort: 32414
              name: gdm-32414
              protocol: UDP
          volumeMounts:              
            - name: hostpath-volume
              mountPath: /movies
              subPath: movies
            - name: hostpath-volume
              mountPath: /tv
              subPath: tv
            - name: hostpath-volume
              mountPath: /music
              subPath: music
            - name: hostpath-volume-config
              mountPath: /config
      volumes:
        - name: hostpath-volume
          persistentVolumeClaim:
            claimName: hostpath-pvc
        - name: hostpath-volume-config
          persistentVolumeClaim:
            claimName: hostpath-config
---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: ClusterIP
  ports:
  - port: 32400               # < port to open on the outside on the server
    targetPort: 32400         # < targetport. port on the pod to passthrough
    name: pms-web             # < reference name for the port in the deployment yaml
    protocol: TCP
  - port: 3005
    targetPort: 3005
    name: plex-companion
  - port: 8324
    name: plex-roku
    targetPort: 8324  
    protocol: TCP  
  - port: 32469
    targetPort: 32469
    name: dlna-tcp
    protocol: TCP
  selector:
    app: plex

---
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
spec:
  ingressClassName: nginx
  rules:
    - host: plex.homelab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
---


