---
### CONFIGMAPS
## INIT-CONTAINER
apiVersion: v1
data:
  ServerConfig.json: |
    {
      "BasePathOverride": "{{ .Values.jackett.ingress.path }}"
    }
  init-jackett.sh: |
    #!/bin/bash
    echo "### Initializing config ###"
    if [ ! -f /jackett-config/ServerConfig.json ]; then
      cp -n /init-jackett/ServerConfig.json /jackett-config/ServerConfig.json
      echo "### No configuration found, intialized with default settings ###"
    fi
kind: ConfigMap
metadata:
  name: init-jackett-cm
---

## APPLICATION
apiVersion: v1
kind: ConfigMap
metadata:
  name: jackett-config
data:
  PGID: 1000
  PUID: 1000

---
### DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jackett
        app: jackett
    spec:
      initContainers:
        - name: config-jackett
          image: docker.io/ubuntu:groovy
          command: ["/init-jackett/init-jackett.sh"]
          volumeMounts:
            - mountPath: /init-jackett
              name: init-files-jackett
            - name: mediaserver-volume
              mountPath: /jackett-config
              subPath: "config/jackett/Jackett"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000 
      containers:
        - name: jackett
          image: docker.io/linuxserver/jackett
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 9117
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - name: jackett-port
              containerPort: 9117
              protocol: TCP
          volumeMounts:
            - name: mediaserver-volume
              mountPath: "/config"
              subPath: "config/jackett"
      volumes:
        - name: mediaserver-volume
          persistentVolumeClaim:
            claimName: pv-claim
        - name: init-files-jackett
          configMap:
            defaultMode: 493
            name: init-jackett-cm

---
### SERVICES
apiVersion: v1
kind: Service
metadata:
  name: jackett
spec:
  type: ClusterIP
  ports:
    - port: 9117
      targetPort: 9117
      protocol: TCP
      name: jackett-port
  selector:
    app: jackett

---
### INGRESS
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
spec:
  ingressClassName: nginx
  rules:
    - host: media.homelab.com
      http:
        paths:
          - path: /jackett
            pathType: Prefix
            backend:
              service:
                name: jackett
                port:
                  number: 9117
---