kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-storage-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: host-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi