apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-storage2
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi