---
- name: Samba Server
  hosts: all
  become: true
  tasks:
#    - name: Update System
#      ansible.builtin.dnf:
#        name: "*"
#        state: latest
    - name: Installing packages
      ansible.builtin.dnf:
        name: cifs-utils, net-tools
    - name: Add the user 'sambauser'
      ansible.builtin.user:
        name: sambauser
        shell: /bin/bash
        groups: users
        append: true
    - name: Create admin group
      ansible.builtin.group:
        name: admin
        state: present
    - name: Create and add user Luiz to admin group
      ansible.builtin.user:
        name: luiz
        shell: /bin/bash
        groups: users,admin
        append: true
    - name: Give sudo access to admin user
      ansible.builtin.blockinfile:
        path: /etc/sudoers
        insertafter: 'root    ALL=(ALL)       ALL'
        block: |
          # Gives sudo access to the admin group
          %admin        ALL=(ALL)       NOPASSWD: ALL

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Permit traffic in default zone for samba service
      ansible.posix.firewalld:
        service: samba
        permanent: true
        state: enabled
    - name: Always reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /srv/samba/datashare
        state: directory

    - name: Mount up device
      ansible.posix.mount:
        path: /srv/samba/datashare
        src: UUID=f1921fef-83aa-4590-aebb-63fe36c308b3
        fstype: ext4
        state: mounted

    - name: Include Samba Server role
      ansible.builtin.include_role:
        name: vladgh.samba.server
      vars:
        samba_netbios_name: Sirius
        samba_server_string: Sirius
        samba_realm: HLSPACE.ORG
        samba_workgroup: WORKGROUP
        samba_load_homes: true
        samba_load_printers: false
        samba_create_varwww_symlinks: true
        samba_log: /var/log/samba.log
        samba_log_size: 60000
        samba_log_level: '3 passdb:5 auth:10 winbind:2 '
        samba_map_to_guest: Never
        samba_users:
          - name: sambauser
            password: sambauser
        samba_username_map:
          - from: 'User Two'
            to: sambauser
        samba_shares_root: /srv/samba
        samba_shares:
          - name: datashare
            public: 'yes'
            comment: 'Public, but only writeable by sambauser'
            write_list: sambauser
            user: sambauser
            group: users
            browseable: 'yes'
