apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    chart: external-dns
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.5
    helm:
      releaseName: external-dns
      values: |
        provider:
          name: cloudflare
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: apiKey
              name: cloudflare-api-key
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default