apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.15.1
    helm:
      releaseName: harbor
      values: |
          expose:
            ingress:
              className: nginx
              annotations:
                cert-manager.io/cluster-issuer: cloudflare-issuer
                external-dns.alpha.kubernetes.io/hostname: registry.hlspace.org
              hosts:
                core: registry.hlspace.org
          externalURL: https://registry.hlspace.org
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default