version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    #network_mode: 'host'
    networks:
      - proxy
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/datashare/media:/media
    environment:
      TZ: America/Sao_Paulo
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.jellyfin.entryPoints=web'
      - 'traefik.http.routers.jellyfin.rule=Host(`jellyfin.hlspace.org`)'


networks:
  proxy:
    external: true

volumes:
  jellyfin_config:
  jellyfin_cache:
