apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  syncPolicy:
    automated:
      selfHeal: true
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.12.0
    helm:
      releaseName: loki
      values: |
        deploymentMode: SingleBinary
        loki:
          commonConfig:
            replication_factor: 1
          storage:
            type: 'filesystem'
          schemaConfig:
            configs:
            - from: "2024-01-01"
              store: tsdb
              index:
                prefix: loki_index_
                period: 24h
              object_store: filesystem # we're storing on filesystem so there's no real persistence here.
              schema: v13
        singleBinary:
          replicas: 1
        read:
          replicas: 0
        backend:
          replicas: 0
        write:
          replicas: 0
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default