- name: update repositories
  apt: update_cache=yes
  changed_when: false
  become: true
- name: Install packages
  apt: name={{item}}
  with_items:
    - htop
    - gimp
    - code
    - discord
    - helm
    - kubectl
    - lens
    - meld
    - mangohud
    - net-tools
    - neofetch
    - notepadqq
    - ntfs-3g
    - onedrive
    - openjdk-19-jdk
    - python3-pip
    - qbittorrent
    - ruby-full
    - vlc
    - telegram-desktop
    - steam
    - git
    - nvtop
    - thunderbird
  become: true
