- name: Add HashiCorp GPG key
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true
- name: Add HashiCorp APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main
    state: present
  become: true
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
  become: true
